### ISSUE TITLE
Crash on Opening Chest

### ISSUE THREAD

**Issue by PiscesdanAT** [raphydaphy/ArcaneMagic#11]
The game crashes when attempting to open a chest (technically the bonus chest at the start, in case that's somehow important). The world was newly generated.

Minecraft Version: 1.14  Snapshot: 19w11b
Fabric Version: fabric-loader-0.4.1+build.125-19w11b.20
Fabric API ver.: 0.2.7+build.122
Silk API ver.: 1.2.3-38
Arcane Magic ver.: 1.0-beta1

[Crash log.](https://pastebin.com/XyKN7uSi)

**Comment by shedaniel** [comment]
Your fabric API is too updated, get 0.2.3 build 111

**Comment by PiscesdanAT** [comment]
That fixed it. Makes sense in hindsight, since I'm using an earlier snapshot. Thank you.
