### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Knito58** [raphydaphy/ArcaneMagic#13]
[crash-2019-04-20_11.24.37-client.txt](https://pastebin.com/515QMXcX)

arcanemagic: 1.0-beta2
Minecraft Version: 1.14 Pre-Release 5
fabric: 0.2.7+build.125

**Comment by raphydaphy** [comment]
You need fabric build 126 for beta 2

**Comment by raphydaphy** [comment]
or the fabric that comes bundled with it. just don't explicitly install fabric api

**Comment by Knito58** [comment]
Thank you! I'll wait until it is up to date. I have just too many mods and my world on the edge - it would be hard to downgrade Fabric. I thought it would play nice with recent snapshot as it was updated only a few hours ago.

**Comment by asiekierka** [comment]
He actually suggested *up*dating Fabric.
