### ISSUE TITLE
Lost game parchement by death: Cannot progress with the mod

### ISSUE THREAD

**Issue by Knito58** [raphydaphy/ArcaneMagic#17]
In survival with vanilla death chest I drowned somewhere in caves and cannot find the chest anymore. The chest contains the starting parchment. Went off with new paper to get another parchment but they don't get written when killing a drowned. The game event flow is lost and I can not progress further.

Steps taken: Kill a drowned. Kill a drowned with paper in inventory.
Killing more drowneds seems not to advance my mod history as they don't initialize another parchment.

What can I do other than starting a new world?

**Comment by PiscesdanAT** [comment]
You should be able to craft a new parchment from a piece of paper and an inksack.

**Comment by Knito58** [comment]
No Sir. Receipe shows up with paper and inksack in REI as "written Parchment". REI doesn't move the items to the grid although I have them. When moved by hand into indicated positions the crafting table output slot stays blank and the item cannot be extracted.

MC 1.14
Arcane Magic v1.0-beta2
Fabric v0.2.7+build.127
Crochet v1.0.2
Cutscene API v1.0.0-beta4

REI's behaviour was already reported [here](https://github.com/shedaniel/RoughlyEnoughItems/issues/71).

**Comment by shedaniel** [comment]
I tested a few recipes with REI and some modded recipes worked.

**Comment by raphydaphy** [comment]
the parchment recipe only unlocks once you have died once while holding a parchment. Perhaps the death chest mod is removing it from your death inv before I check ... :thinking:

**Comment by Knito58** [comment]
Yep. Now it is somewhere in the world and not craftable anymore. Not for me. Maybe it works for everybody else. @shedaniel: Yes. In some few cases the modded recipes do work. Mostly not. Maybe that is an issue due to when and how recipes get declared to the game.
The parchment not being craftable is not an issue where I would blame REI for.
Anyways I didn't want to bark here. Just report a problem with an early game and be helpful. It is not a problem for me to start over with a new world. I'm cool. 8)

**Comment by raphydaphy** [comment]
By the way you can also use /arcanemagic reset @p to restart the mod at any
point, but the issue is fixed now for future builds

**Comment by Knito58** [comment]
Thank you very much.
