### ISSUE TITLE
Notebook lost "next-page-button" after a trip to the nether.

### ISSUE THREAD

**Issue by Knito58** [raphydaphy/ArcaneMagic#18]
I'm still early stage in the mod and consult the note book a lot. The smelter refuses bein crafted and on search for a "more powerful" scepter I went to the nether to load it even fuller with lots of souls of pigmen.

After return to overworld when consulting the note book the greeting page opens. The little arrow button "next page" in the lower right corner was missing. The book could not be read further any more as the index was not reachable. 

After a "Save and Quit to title" and loading the world again the button was back.

AM 1.0-beta2 on MC 1.14 with F 0.2.7 build 127

**Comment by raphydaphy** [comment]
Fixed in Crochet 1.0.4 https://minecraft.curseforge.com/projects/crochet/files/2712636
