### ISSUE TITLE
Changing dimensions temporarily removes all Notebook info

### ISSUE THREAD

**Issue by GottJammern** [raphydaphy/ArcaneMagic#20]
Portaling from Overworld to Nether or vice versa removes all content on the right hand page of the Notebook - it appears totally blank. This seems to occur regardless of whether the Notebook was in inventory or not.

-Untested with the End.
FIX: Exiting and re-entering the world resolves the issue until next trip.

**Comment by raphydaphy** [comment]
right, I've had this mentioned a lot but no-one actually reported it until now. Thanks I will fix it

**Comment by raphydaphy** [comment]
Fixed in Crochet 1.0.4 https://minecraft.curseforge.com/projects/crochet/files/2712636
