### ISSUE TITLE
How to use the altar ?

### ISSUE THREAD

**Issue by LeQwouincy** [raphydaphy/ArcaneMagic#22]
As said in the title, i can't find how to use the altar...

**Comment by raphydaphy** [comment]
Right click with a soul pendant to put it in the altar, then kill something within 1 or 2 blocks from the altar and it will drop no items but add soul to the pendant

**Comment by LeQwouincy** [comment]
After a lot of try i found that most of hostile mobs(all of the undeads at least) don't give souls with the altar.
Is it a bug or meant to be like that ? (because you can use scepter on undeads)
If it's not a bug perhaps write  something in the book to precise it

**Comment by raphydaphy** [comment]
they need to have less than 30 health

**Comment by raphydaphy** [comment]
and for scepter they need to have two health less than you or less

**Comment by LeQwouincy** [comment]
So i don't why killing zombies near the altar don't put soul in the pendant

**Comment by raphydaphy** [comment]
they basically need to be standing on top of it - the altar will be reworked soon anyway because its very difficult to use with any level of efectivness

**Comment by LeQwouincy** [comment]
i've also tried this before but still have no effect.
i'm just going to make a chicken factory

**Comment by raphydaphy** [comment]
it should certainly work if the zombies are standing on top of the altar when they die.. if its not something must be wrong or a mod is adjusting health

**Comment by LeQwouincy** [comment]
But if you're going to rework the altar no problem. I think it will be corrected at this moment.
