### ISSUE TITLE
Compatibility with optifine

### ISSUE THREAD

**Issue by TimGoll** [raphydaphy/ArcaneMagic#23]
https://github.com/modmuss50/OptiFabric/issues/5

Is there any plan on solving this issue?

**Comment by raphydaphy** [comment]
yea I was waiting for a cactus to grow but I guess I can look at it tomorrow instead

**Comment by TimGoll** [comment]
I did not want to sound pressing :D

**Comment by raphydaphy** [comment]
no don't worry it was a joke, thanks for reminding me to fix this :P

**Comment by rapus95** [comment]
Is this still unsolved? 👼

**Comment by raphydaphy** [comment]
its fixed in the laest build, I just forgot to close this
