### ISSUE TITLE
Crash on recipe view

### ISSUE THREAD

**Issue by lagonnebula** [raphydaphy/ArcaneMagic#26]
Hello,

When i press the key for the recipe view on REI for an item from underground biome, i got this error :
https://pastebin.com/bTHFuSQB
And the error come from ArcaneMagic, i tried removing the mod and the view recipe worked perfectly.

I have Refined Machine, Underground Biome and Arcane Magic installed

**Comment by raphydaphy** [comment]
hm oh yea this is fixed in dev i will publish a release soon

**Comment by lagonnebula** [comment]
Oh ok ! Nice !
